### PR TITLE
Make enableRetry configurable for Retry V2 middleware

### PR DESCRIPTION
**Pull request by smartinio**
### Context
We want to use the retry middleware for GraphQL clients via mappersmith

### Problem
- The default Retry middleware only retries GET requests
- GraphQL uses POST requests to query data

### Solution
Make `enableRetry` configurable, keeping the default behavior to stay backward compatible.
This way, graphQL queries can be retried if configured accordingly:
```javascript
import Retry from 'mappersmith/middleware/retry/v2'

const retryConfigs = {
  enableRetry: (request) => request.path().endsWith('/graphql') && request.body().query.startsWith('query'),
  validateRetry: (response) => response.responseStatus >= 500,
}

const client = forge({
  middleware: [ Retry(retryConfigs) ],
  /* ... */
})
```

### CODE REVIEW

**Comment by klippx** [comment]
See #218 for some prior discussion on this topic.

Currently, mappersmith still has a bit of work to be "graphql ready", the approach we have is to use [correct HTTP semantics](https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#rfc.section.9.2.2.p.4) which means POST requests should not be retried.

With that said, I think it would be better if this was a new middleware specific rather than modifying the existing. Perhaps as a `RetryGraphqlMiddleware`. But this PR is still lacking, because it would retry `mutations` as well as `query`, right?

I think it would be better to create the middleware in your repo and wait and see if mappersmith provides some better tooling for graphql in the future.

**Comment by smartinio** [comment]
> Currently, mappersmith still has a bit of work to be "graphql ready", the approach we have is to use correct HTTP semantics which means POST requests should not be retried.

Sure, but where's the harm in letting this be configurable? If I know that an outgoing POST request is idempotent, the library shouldn't get in the way. The default behavior is still there, so I don't see anyone blaming mappersmith for e.g. duplicated resources, when they've deliberately overridden the default check.

> With that said, I think it would be better if this was a new middleware specific rather than modifying the existing. Perhaps as a RetryGraphqlMiddleware.

That could work, but it's also more work. I don't see a problem with extending the current one in this way. There are already several configuration parameters similar to this one.

> But this PR is still lacking, because it would retry mutations as well as query, right?

This PR doesn't change any behavior in Mappersmith. It just allows this piece of the middleware to be configurable. The example use-case in the description should not retry mutations, no, since the second part of the check would fail:
```javascript
enableRetry: (request) => request.path().endsWith('/graphql') && request.body().query.startsWith('query'),
```

**Comment by klippx** [comment]
`enableRetry: (request) => request.path().endsWith('/graphql') && request.body().query.startsWith('query'),`

It is not that simple:
- path doesnt have to be end in `/graphql` (I know you know this too, just pointing it out)
- you can have a body json: `{ query: "query X() {...} mutation Y() {...}", operationName: "Y" }` and your logic would accept a mutation as a retryable operation

The problem for me is that this is left as an exercise to the reader, it's hard for them to test that it works as they expect. And they might shoot themselves in the process, like my example above.

It is easy to say "what is the harm" and "why not make it configurable" but I think the RetryMiddleware today is already a bit complex and adding this extra flexibility without any tests is going to give people headaches instead of solving their problems. 

Going back to the `RetryGraphqlMiddleware` idea; in a Graphql context it would be theoretically possible to retry certain POST requests out of the box in a meaningful way. While also being able to provide tests for it, and documentation how it works. It could be easy to use, and people will not having to worry about testing retry fn themselves in every client times every service that uses this middleware. Which is to say that the middleware itself provides some guarantees given some constraints (`query` not `mutation` like discussed).

But I still think something is lacking in mappersmith before we can do this in a meaningful way. Such as, being able to specify that your client is of `graphql` color when forging it. And the fact that making this really good might require a lot more `graphql` libs to parse the query to extract operationName, variables, operationType etc.

**Comment by smartinio** [comment]
Wasn't aware that GraphQL supported queries and mutations in the same request, is that really a thing? That would make it slightly more complex to verify, yeah. I'll look into creating something more robust, then. But can keep this open for some time to see if any more discussion arises. Thanks for the response!

**Comment by klippx** [comment]
Yes, it is a thing. The official docs doesn't describe it well but [it is mentioned](https://graphql.org/learn/queries/#operation-name) but here is a resource that [describes it better](https://dgraph.io/docs/graphql/api/multiples/#multiple-operations)

**Comment by klippx** [comment]
Closing with suggestion to try this out in a separate middleware before submitting a PR 🙏

**Pull request closed without merging**
