### PR TITLE
allow path params without encodeURIComponent

### PR DESCRIPTION
**Pull request by jbeuckm**
Workaround for https://github.com/tulios/mappersmith/issues/159

### CODE REVIEW

**Comment by tulios** [comment]
That works, it's an interesting use case you have there 😄

**Comment by klippx** [comment]
How would we use this? I think that needs to be added to readme, this is a feature that should be documented so people will find it easy to find and use.

Because we could discuss a bit how we want to use it. I can almost see it being a little more granular, such as:

```
export const createAPI = forge({
  clientId: 'client',
  host: 'somehost',
  resources: {
    Parts: {
      get: { path: '/api/{parts}.json', method: 'get', encodeDynamicSegments: false },
    }
  }
})
```

Or even more granular:

```
      get: { path: '/api/{warehouse}/picker/{parts}.json', method: 'get', staticSegments: ['parts'] },
```

where only key === 'parts' gets to skip encoding while key === 'warehouse' behaves as normal.

Just some thoughts, WDYT @jbeuckm ?

**Comment by jbeuckm** [comment]
The first code block for `Parts.get` above is the intended usage. This was a workaround that seemed to fit the current api, but starts down the road of being overly specific in MethodDescriptor options. I think we would get a lot more flexibility by allowing a function for 'path' that takes the arguments passed and generates a string.

**Comment by jbeuckm** [comment]
This is more flexible: https://github.com/tulios/mappersmith/pull/186/files

**Comment by tulios** [comment]
I merged #186 instead, thanks @jbeuckm, and sorry for the long delay.

**Comment by jbeuckm** [comment]
> I merged #186 instead, thanks @jbeuckm, and sorry for the long delay.

Thanks! I meant to close this old one.

**Pull request closed without merging**
