### PR TITLE
add custom headers for vanilla browser gateway

### PR DESCRIPTION
**Pull request by icewind1991**
Makes the vanilla gateway properly set any custom headers

### CODE REVIEW

**Comment by tulios** [comment]
Hi @icewind1991, I already had a pull request including headers to `VanillaGateway` so I decided to merge both implementations, thanks!

**Comment by CezarLuiz0** [comment]
When you will publish the new version in npm? Thanks!

**Comment by tulios** [comment]
This was released in version [0.9.0](https://github.com/tulios/mappersmith/blob/master/CHANGELOG.md#090), the new ways to include headers will be released this week at most.

**Comment by CezarLuiz0** [comment]
Sorry, I'm building a project and I needed the headers release.

Thanks!

**Pull request closed without merging**
